# Generated by Django 4.0.8 on 2023-01-25 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='sub_catagories',
        ),
        migrations.AlterField(
            model_name='blog',
            name='catagories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.catagory'),
        ),
    ]
