# Generated by Django 4.0.8 on 2023-01-26 12:52

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blog_sub_catagories_alter_blog_catagories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='category_parent',
        ),
        migrations.AddField(
            model_name='catagory',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catagory',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catagory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.catagory'),
        ),
        migrations.AddField(
            model_name='catagory',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catagory',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
