# Generated by Django 4.0.8 on 2023-02-03 16:08

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_catagory_image_catagory_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='level',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='catagory',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='catagory',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.CreateModel(
            name='Catagorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.catagorys')),
            ],
            options={
                'verbose_name_plural': 'Catagory',
            },
        ),
    ]
